apiVersion: skaffold/v2beta19
kind: Config
build:
  artifacts:
    - image: reg.istry.cz/tergum-misc/tergum-ca-certificates
      context: ../docker/tergum-ca-certificates
      kaniko:
        cache: {}
    - image: reg.istry.cz/tergum-misc/postgres
      context: ../docker/postgres
      kaniko:
        cache: {}
    - image: reg.istry.cz/tergum-misc/mysql
      context: ../docker/mysql
      kaniko:
        cache: {}
    - image: reg.istry.cz/tergum-misc/postgres-with-tergum
      context: ../docker/postgres-with-tergum
      kaniko:
        cache: {}
    - image: reg.istry.cz/tergum-misc/mysql-with-tergum
      context: ../docker/mysql-with-tergum
      kaniko:
        cache: {}
  cluster: {}
deploy:
  kubectl:
    manifests:
      - k8s/*
