Meta:
  SchemaVersion: 3
Telemetry:
  CollectBackupLog: true
Notification:
  Targets:
    - SlackWebhook:
        SendOK: true
        URLs:
          - http://127.0.0.1:9999 # Slack webhook proxy
          - https://hooks.slack.com/services/xxx/yyy/zzz
Backups:
  - ID: example-dir
    Source:
      Dir:
        Path: misc/example/config
    Targets:
      - ID: filepath
        FilePath:
          Path: tmp/config.tar
      - ID: filepath-gz
        Middlewares:
          - Gzip: {}
        FilePath:
          Path: tmp/config.tar.gz
