Meta:
  SchemaVersion: 3
Backups:
  - ID: notion-html
    Source:
      Notion: &notion
        Token: ---notion_token_v2---
        SpaceID: ---notion_space_id---
        Format: html
    Targets:
      - ID: filepath
        FilePath:
          Path: tmp/notion-html.zip
  - ID: notion-md
    Source:
      Notion:
        <<: *notion
        Format: markdown
    Targets:
      - ID: filepath
        FilePath:
          Path: tmp/notion-md.zip
