Meta:
  SchemaVersion: 3
Backups:
  - ID: example-dir
    Source:
      Dir:
        Path: misc/example/config
    Targets:
      - ID: filepath
        FilePath:
          Path: tmp/config.tar
      - ID: filepath-gz
        Middlewares:
          - Gzip: {}
        FilePath:
          Path: tmp/config.tar.gz
