Meta:
  SchemaVersion: 3
Backups:
  - ID: example-ftp
    Source:
      FTP:
        Host: 127.0.0.1
        User: foo
        Password: bar
    Targets:
      - ID: filepath
        FilePath:
          Path: tmp/ftp.tar
