Meta:
  SchemaVersion: 3
Backups:
  - ID: example-postgres-server
    Source:
      PostgresServer:
        Host: 127.0.0.1
        Port: 5432
        User: postgres
        Password: pg
    Targets:
      - ID: filepath
        FilePath:
          Path: tmp/postgres-server.sql
