Meta:
  SchemaVersion: 3
Telemetry:
  CollectBackupLog: true
Backups:
  - ID: example-kubernetes
    Source:
      Kubernetes:
        Server: http://127.0.0.1:8001
        Token: foo-bar-baz
        Namespace: default
        Resource: configmap
    Targets:
      - ID: filepath
        FilePath:
          Path: tmp/kubernetes-configmaps.yaml
