Meta:
  SchemaVersion: 3
Backups:
  - ID: example-ftp
    Source:
      FTP:
        Host: ftp.dlptest.com
        User: dlpuser
        Password: rNrKYTX9g7z3RgJRmxWuGHbeu
    Targets:
      - ID: filepath
        FilePath:
          Path: tmp/ftp.tar
