apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  clusterIP: None
  ports:
    - name: console
      port: 9001
      protocol: TCP
      targetPort: 9001
    - name: api
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: minio
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  serviceName: minio
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: main
          image: minio/minio
          args:
            - server
            - /data
            - --console-address
            - :9001
          ports:
            - containerPort: 9001
            - containerPort: 9000
          env:
            - name: MINIO_ROOT_USER
              value: admin
            - name: MINIO_ROOT_PASSWORD
              value: asdfasdf
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
            # limits:
            #   memory: 20Mi
            #   cpu: 20m
        - name: create-buckets
          image: minio/mc
          command:
            - /bin/sh
            - -c
          args:
            - |-
              sleep 10;
              /usr/bin/mc config host add default http://localhost:9000 admin asdfasdf;
              /usr/bin/mc rm -r --force default/tergum-backups;
              /usr/bin/mc mb default/tergum-backups;
              /usr/bin/mc policy default myminio/tergum-backups;
              sleep 10000000;
              exit 0;
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
            # limits:
            #   memory: 20Mi
            #   cpu: 20m
