apiVersion: v1
kind: ConfigMap
metadata:
  name: tergum
data:
  tergum.yaml: |-
    Meta:
      SchemaVersion: 3
    Notification:
      Backend:
        Email:
          SmtpHost: maildev
          SmtpPort: 1025
          Username: null
          Password: null
          From: tergum@example.com
      Targets:
        - Email:
            Emails:
              - ondrej+k8s-job@example.com
              - monitoring+k8s-job@example.com
    Backups:
      - ID: example-postgres
        RemoteExec:
          Server: http://127.0.0.1:8000
        Source:
          Postgres:
            Host: postgres
            Port:  5432
            User: postgres
            Password: pg
            Database: postgres
        Targets:
          - ID: s3
            Middlewares:
              - Gzip: {}
            S3:
              AccessKey: admin
              SecretKey: asdfasdf
              Endpoint: http://minio:9000
              BucketName: tergum-backups
              Prefix: example-postgres
              Suffix: sql.gz
      - ID: example-mysql
        RemoteExec:
          Server: http://127.0.0.1:8001
        Source:
          Mysql:
            Host: mysql
            Port:  3306
            User: root
            Password: root
            Database: default
        Targets:
          - ID: s3
            Middlewares:
              - Gzip: {}
            S3:
              AccessKey: admin
              SecretKey: asdfasdf
              Endpoint: http://minio:9000
              BucketName: tergum-backups
              Prefix: example-mysql
              Suffix: sql.gz
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tergum
spec:
  schedule: "*/1 * * * *"
  failedJobsHistoryLimit: 10
  successfulJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: config
              configMap:
                name: tergum
          containers:
            - name: main
              image: reg.istry.cz/tergum-misc/tergum-ca-certificates
              args:
                - /bin/bash
                - -c
                - sleep 10 && tergum backup -c /config/tergum.yaml
              volumeMounts:
              - name: config
                mountPath: /config
            - name: postgres
              image: reg.istry.cz/tergum-misc/postgres-with-tergum
              args:
                - tergum
                - server
                - -a
                - :8000
            - name: mysql
              image: reg.istry.cz/tergum-misc/mysql-with-tergum
              args:
                - tergum
                - server
                - -a
                - :8001
          restartPolicy: OnFailure
